import numpy as np

# background_remove
BACKGROUND_GOOD_THRESHOLD = 60

# lk_tracker
TRACK_WINDOW_SIZE = 31  # Must be an odd number
GAUSS_BLUR_WINDOW_SIZE = 17
PYRAMID_DEPTH = 3
PIXEL_TO_TRACK = np.array([109, 300])
NUM_FRAMES_TO_TRACK = 200
# GAUSS_STDDEV = 2.5

# utils
GAUSS_STDDEV = 2.5

# video_stitch
PERSON_VIDEO = 'Person.mp4'
PERSON_BACKGROUND_FRAME = 5
ARTIFICIAL_SHADOW_OFFSET = [0, 50]
ARTIFICIAL_SHADOW_COLOUR = 30

SHADOW_VIDEO = 'Shadow1.mp4'
SHADOW_BACKGROUND_FRAME = 10
SHADOW_THRESHOLD = 120
LAPLACIAN_BLUR_WINDOW_SIZE = 4
SHADOW_SIZE = [400, 80]
